#!/bin/sh

[ -z "${DIR}" ] && DIR=.
[ -z "${CLANG_FORMAT}" ] && CLANG_FORMAT=clang-format
[ -z "${INCLUDE}" ] && INCLUDE="\.(c|c\+\+|cc|cpp|cxx|h|h\+\+|hh|hpp|hxx|inc)$"

included_files() {
    find "${DIR}" -type f | grep -E "${INCLUDE}"
}

files() {
    if [ -z "${EXCLUDE}" ]; then
        included_files
    else
        included_files | grep -Ev "${EXCLUDE}"
    fi
}

if [ -z "${FORMAT}" ]; then
    diffs=$(mktemp)
    files | while IFS= read -r file; do
        "${CLANG_FORMAT}" -style=file "${file}" | diff -u "${file}" - || echo "${file}" >> "${diffs}"
    done
    if [ -s "${diffs}" ]; then
        exit 1
    fi
else
    files | xargs "${CLANG_FORMAT}" -style=file -i
fi
