#!/bin/sh

[ -z "${DIR}" ] && DIR=.
[ -z "${CLANG_FORMAT}" ] && CLANG_FORMAT=clang-format
[ -z "${INCLUDE}" ] && INCLUDE="\.(c|c\+\+|cc|cpp|cxx|h|h\+\+|hh|hpp|hxx|inc)$"

included_files() {
    find "${DIR}" -type f | grep -Ei "${INCLUDE}"
}

files() {
    [ -z "${EXCLUDE}" ] && included_files || included_files | grep -Eiv "${EXCLUDE}"
}

if [ -z "${FORMAT}" ]; then
    diffs=$(mktemp)
    files | while read file; do
        "${CLANG_FORMAT}" -style=file "${file}" | diff -u "${file}" - || echo "${file}" >> "${diffs}"
    done
    [ -s "${diffs}" ] && exit 1 || exit 0
fi

files | xargs "${CLANG_FORMAT}" -style=file -i
