#!/usr/bin/env bash
set -euo pipefail

DIR="$1"
shift

find "${DIR}" -type f \( -iname \*.cpp -or -iname \*.hpp -or -iname \*.c -or -iname \*.h \) \
    | while read -r file; do
        clang-format "$@" "${file}" | diff -u "${file}" -
    done
