#!/usr/bin/env bash
set -uo pipefail

EXIT=0
DIR="$1"
shift

while read -r file; do
    if ! clang-format "$@" "${file}" | colordiff -u "${file}" -; then
        EXIT=1
    fi
done < <(find "${DIR}" -type f \( -iname \*.cpp -or -iname \*.hpp -or -iname \*.c -or -iname \*.h \))

exit ${EXIT}
