#!/usr/bin/env bash
set -euo pipefail

print_help() {
    echo "Usage: cppy {format,format-check,lint} directory"
}

cpp_files() {
    find "$1" -type f \
        -iname \*.c -o \
        -iname \*.c++ -o \
        -iname \*.cc -o \
        -iname \*.cpp -o \
        -iname \*.cxx -o \
        -iname \*.h -o \
        -iname \*.h++ -o \
        -iname \*.hh -o \
        -iname \*.hpp -o \
        -iname \*.hxx
}

if [[ $# -lt 2 ]]; then
    print_help
    exit 1
fi

tool=$1
directory=$2
shift
shift

case "${tool}" in
format)
    cpp_files "${directory}" | xargs clang-format -i "$@"
    ;;
format-check)
    code=0
    while read -r file; do
        if ! clang-format "$@" "${file}" | colordiff -u "${file}" -; then
            code=1
        fi
    done < <(cpp_files "${directory}")
    exit ${code}
    ;;
tidy)
    cpp_files "${directory}" | xargs clang-tidy "$@"
    ;;
*)
    print_help
    exit 1
    ;;
esac
