#!/usr/bin/env bash
set -euo pipefail

tool=$1
files=$(mktemp)
find "$2" -type f \
    -iname \*.c -o \
    -iname \*.c++ -o \
    -iname \*.cc -o \
    -iname \*.cpp -o \
    -iname \*.cxx -o \
    -iname \*.h -o \
    -iname \*.h++ -o \
    -iname \*.hh -o \
    -iname \*.hpp -o \
    -iname \*.hxx > "${files}"
shift
shift

case "${tool}" in
format)
    xargs clang-format -i "$@" < "${files}"
    ;;
check)
    code=0
    while read -r file; do
        clang-format "$@" "${file}" | ${DIFF:=diff} -u "${file}" - || code=1
    done < "${files}"
    exit ${code}
    ;;
*)
    exit 1
esac