#!/usr/bin/env bash
set -euo pipefail

files() {
    find "$1" -type f \
        -iname \*.c -o \
        -iname \*.c++ -o \
        -iname \*.cc -o \
        -iname \*.cpp -o \
        -iname \*.cxx -o \
        -iname \*.h -o \
        -iname \*.h++ -o \
        -iname \*.hh -o \
        -iname \*.hpp -o \
        -iname \*.hxx
}

: "${CLANG_FORMAT:=clang-format}"

if [[ "$1" == "--check" ]]; then
    code=0
    while read -r file; do
        "${CLANG_FORMAT}" -style=file "${file}" | "${DIFF:=diff}" -u "${file}" - || code=1
    done < <(files "$2")
    exit ${code}
fi

files "$1" | xargs "${CLANG_FORMAT}" -style=file -i
