#!/usr/bin/env bash
set -euo pipefail

files() {
    find "${DIRECTORY}" -type f ${IGNORE} \
        \( \
        -iname \*.c -o \
        -iname \*.c++ -o \
        -iname \*.cc -o \
        -iname \*.cpp -o \
        -iname \*.cxx -o \
        -iname \*.h -o \
        -iname \*.h++ -o \
        -iname \*.hh -o \
        -iname \*.hpp -o \
        -iname \*.hxx \
        \)
}

: "${CLANG_FORMAT:=clang-format}"
: "${DIFF:=diff}"
IGNORE=""
CHECK=false
DIRECTORY="."

while [[ $# -gt 0 ]]; do
    case "$1" in
    --check)
        CHECK=true
        shift
        ;;
    --ignore)
        IGNORE="$IGNORE ! -name $2"
        shift
        shift
        ;;
    *)
        DIRECTORY="$1"
        shift
        ;;
    esac
done

if [[ $CHECK == true ]]; then
    code=0
    while read -r file; do
        "${CLANG_FORMAT}" -style=file "${file}" | "${DIFF}" -u "${file}" - || code=1
    done < <(files)
    exit ${code}
fi

files | xargs "${CLANG_FORMAT}" -style=file -i
